# Модуль 1
kind = str("яблоко")
amount = int("3")
grade = ("зеленые","красные", "желтые","вкусные")
coast = float("50.5")
index = bool(amount > 1)
print(kind)
print('колличество яблок:',amount)
print("Виды яблок:",grade)
print ('Цена:',coast,"руб/кг")
print('Яблок больше двух?',index)
print('Типы переменных: kind, amount, coast,index')
print(type(kind))
print(type(amount))
print(type(coast))
print(type(index))
